[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NPM_CONFIG_PRODUCTION = "false"
  NODE_ENV = "development"


